#!/usr/bin/env bash
# =============================================================================
# PIC-SURE All-in-One — Preflight Checks
# =============================================================================
# Non-mutating host/config validation for init.sh and update.sh.
#
# Usage:
#   ./preflight.sh
#   ./preflight.sh --network
#   ./preflight.sh --json      # machine-readable output (see docs/cli-contract.md)
#
# Exits 1 if any check fails (both modes); warnings do not fail the run.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
PICSURE_ROOT="$SCRIPT_DIR"
export PICSURE_ROOT

LOG_PREFIX="preflight"
# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/scripts/lib/common.sh"

# shellcheck source=scripts/picsure-compose.sh
source "$SCRIPT_DIR/scripts/picsure-compose.sh"

# shellcheck source=scripts/lib/json.sh
source "$SCRIPT_DIR/scripts/lib/json.sh"

NETWORK=false
FAILED=false
JSON=false
CHECKS=()
DAEMON_OK=false

# Detect --json first so result helpers know the mode even if an unknown
# option appears before it on the command line.
for arg in "$@"; do
  case "$arg" in
    --json) JSON=true ;;
  esac
done

# Each check has a stable name (documented in docs/cli-contract.md) plus a
# human message. Human mode prints exactly what it always did; JSON mode
# accumulates {name, status, message} objects instead.
add_check() {
  CHECKS+=("$(json_obj "$(json_str name "$1")" "$(json_str status "$2")" "$(json_str message "$3")")")
}

ok() {
  local name="$1"
  shift
  if [ "$JSON" = "true" ]; then
    add_check "$name" ok "$*"
  else
    echo -e "${PICSURE_GREEN}[ok]${PICSURE_NC} $*"
  fi
}

warn() {
  local name="$1"
  shift
  if [ "$JSON" = "true" ]; then
    add_check "$name" warn "$*"
  else
    echo -e "${PICSURE_YELLOW}[warn]${PICSURE_NC} $*"
  fi
}

fail() {
  local name="$1"
  shift
  FAILED=true
  if [ "$JSON" = "true" ]; then
    add_check "$name" fail "$*"
  else
    echo -e "${PICSURE_RED}[fail]${PICSURE_NC} $*" >&2
  fi
}

psection() {
  if [ "$JSON" != "true" ]; then
    echo "[preflight] $*"
  fi
}

for arg in "$@"; do
  case "$arg" in
    --network) NETWORK=true ;;
    --json) ;;
    -h|--help)
      sed -n '2,13p' "$0"
      exit 0
      ;;
    *)
      fail "args.unknown" "Unknown option: $arg"
      ;;
  esac
done

check_command() {
  local name="$1"
  local cmd="$2"
  local label="${3:-$2}"

  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$name" "$label found: $(command -v "$cmd")"
  else
    fail "$name" "$label not found."
  fi
}

check_required_env() {
  local key="$1"
  local value="${!key:-}"

  if [ -n "$value" ]; then
    ok "env.$key" "$key is set."
  else
    warn "env.$key" "$key is not set."
  fi
}

compose_config_ready() {
  local missing
  missing="$(picsure_compose_missing_generated_files "$SCRIPT_DIR" || true)"

  if [ -z "$missing" ]; then
    return 0
  fi

  while IFS= read -r path; do
    warn "compose.generated" "$path is generated by ./init.sh and is not present yet."
  done <<< "$missing"
  return 1
}

emit_json() {
  local top=()
  top+=("$(json_raw schema_version 1)")
  top+=("$(json_str command preflight)")
  top+=("$(json_bool network_checked "$NETWORK")")
  if [ "$FAILED" = "true" ]; then
    top+=("$(json_bool passed false)")
  else
    top+=("$(json_bool passed true)")
  fi
  top+=("$(json_raw checks "$(json_arr ${CHECKS[@]+"${CHECKS[@]}"})")")
  json_obj "${top[@]}"
  echo ""
}

cd "$SCRIPT_DIR"

psection "Host tools"
check_command host.git git Git
check_command host.docker docker Docker

if command -v uuidgen >/dev/null 2>&1; then
  ok host.uuid "UUID generation available through uuidgen."
elif [ -f /proc/sys/kernel/random/uuid ]; then
  ok host.uuid "UUID generation available through /proc/sys/kernel/random/uuid."
else
  fail host.uuid "UUID generation unavailable. Install uuidgen."
fi

if command -v jq >/dev/null 2>&1; then
  ok host.jq "jq found: $(command -v jq)"
else
  warn host.jq "jq not found; release-control.sh will use Docker image ${JQ_IMAGE:-ghcr.io/jqlang/jq:1.7.1}."
fi

if docker compose version >/dev/null 2>&1; then
  ok host.compose "Docker Compose available: $(docker compose version --short 2>/dev/null || docker compose version)"
else
  fail host.compose "Docker Compose V2 is not available through 'docker compose'."
fi

if docker info >/dev/null 2>&1; then
  DAEMON_OK=true
  ok host.daemon "Docker daemon is reachable."
else
  fail host.daemon "Docker daemon is not reachable."
fi

psection "Files"
for path in docker-compose.yml init.sh update.sh build-images.sh release-control.sh run-migrations.sh seed-db.sh config/scripts/generate-introspection-token.sh; do
  if [ -f "$path" ]; then
    ok "files.$path" "$path exists."
  else
    fail "files.$path" "$path is missing."
  fi
done

for path in init.sh update.sh build-images.sh release-control.sh run-migrations.sh seed-db.sh config/scripts/generate-introspection-token.sh; do
  if [ -x "$path" ]; then
    ok "exec.$path" "$path is executable."
  else
    fail "exec.$path" "$path is not executable."
  fi
done

psection "Shell syntax"
for path in init.sh update.sh build-images.sh preflight.sh status.sh uninstall.sh release-control.sh bootstrap-remote-db.sh run-migrations.sh seed-db.sh load-demo-data.sh etl.sh scripts/lib/common.sh scripts/lib/json.sh scripts/picsure-compose.sh scripts/env-set.sh scripts/compose.sh scripts/db-wait.sh config/scripts/generate-introspection-token.sh; do
  if [ -f "$path" ]; then
    if bash -n "$path"; then
      ok "syntax.$path" "$path syntax is valid."
    else
      fail "syntax.$path" "$path has a shell syntax error."
    fi
  fi
done

psection "Environment"
if [ -f "$ENV_FILE" ]; then
  ok env.present ".env exists."
  if picsure_load_env "$ENV_FILE" 2>/dev/null; then
    check_required_env AUTH0_CLIENT_ID
    check_required_env AUTH0_CLIENT_SECRET
    check_required_env AUTH0_TENANT
    check_required_env ADMIN_EMAIL

    case "${DB_MODE:-local}" in
      local|remote) ok env.db_mode "DB_MODE=${DB_MODE:-local}" ;;
      *) fail env.db_mode "DB_MODE must be local or remote, got '${DB_MODE}'." ;;
    esac

    if [ "${DB_MODE:-local}" = "remote" ]; then
      check_required_env DB_HOST
      check_required_env DB_ROOT_USER
      check_required_env DB_ROOT_PASSWORD
    fi

    case "${AUTH_MODE:-required}" in
      required|open|explore) ok env.auth_mode "AUTH_MODE=${AUTH_MODE:-required}" ;;
      *) fail env.auth_mode "AUTH_MODE must be required, open, or explore, got '${AUTH_MODE}'." ;;
    esac
  else
    fail env.parse ".env is not valid shell syntax; fix or regenerate it."
  fi
else
  warn env.present ".env is missing. Run: cp .env.example .env"
fi

psection "Compose"
if [ "$DAEMON_OK" != "true" ]; then
  warn compose.config "Skipping Compose config validation; Docker daemon is not reachable."
elif compose_config_ready; then
  if picsure_compose config --quiet; then
    ok compose.config "Compose config is valid."
  else
    fail compose.config "Compose config is invalid."
  fi
else
  warn compose.config "Skipping Compose config validation until generated init files exist."
fi

psection "Release control"
release_repo="${RELEASE_CONTROL_REPO:-https://github.com/hms-dbmi/pic-sure-baseline-release-control}"
release_branch="${RELEASE_CONTROL_BRANCH:-main}"
ok release.repo "RELEASE_CONTROL_REPO=$release_repo"
ok release.branch "RELEASE_CONTROL_BRANCH=$release_branch"

if [ -d "$SCRIPT_DIR/.data/release-control/.git" ]; then
  ok release.cache "Release-control cache exists at .data/release-control."
else
  warn release.cache "Release-control cache is missing; init/update will clone it."
fi

psection "JWT creator"
jwt_repo="${JWT_CREATOR_REPO:-https://github.com/hms-dbmi/jwt-creator.git}"
jwt_ref="${JWT_CREATOR_REF:-v1.0.0}"
jwt_dir="${JWT_CREATOR_DIR:-$SCRIPT_DIR/.data/jwt-creator}"
ok jwt.repo "JWT_CREATOR_REPO=$jwt_repo"
if [ "$jwt_ref" = "v1.0.0" ]; then
  ok jwt.ref "JWT_CREATOR_REF=$jwt_ref"
else
  warn jwt.ref "JWT_CREATOR_REF=$jwt_ref (default is v1.0.0)."
fi

if [ -f "$jwt_dir/target/generateJwt.jar" ]; then
  ok jwt.jar "jwt-creator jar is cached."
else
  warn jwt.jar "jwt-creator jar is not cached; first token generation will clone/build it with Docker."
fi

if [ "$NETWORK" = "true" ]; then
  psection "Network"
  if git ls-remote --heads "$release_repo" "$release_branch" >/dev/null 2>&1 || git ls-remote --tags "$release_repo" "$release_branch" >/dev/null 2>&1; then
    ok network.release-control "Release-control ref is reachable."
  else
    fail network.release-control "Release-control branch/tag '$release_branch' is not reachable at $release_repo."
  fi

  if git ls-remote --tags "$jwt_repo" "$jwt_ref" >/dev/null 2>&1 || git ls-remote --heads "$jwt_repo" "$jwt_ref" >/dev/null 2>&1; then
    ok network.jwt-creator "jwt-creator ref is reachable."
  else
    fail network.jwt-creator "jwt-creator ref '$jwt_ref' is not reachable at $jwt_repo."
  fi
else
  warn network.skipped "Skipping network checks. Use --network to verify remote release-control and jwt-creator refs."
fi

if [ "$JSON" = "true" ]; then
  emit_json
  if [ "$FAILED" = "true" ]; then
    exit 1
  fi
  exit 0
fi

if [ "$FAILED" = "true" ]; then
  echo "[preflight] Failed." >&2
  exit 1
fi

echo "[preflight] Passed."
