#!/usr/bin/env bash
# =============================================================================
# PIC-SURE All-in-One — Preflight Checks
# =============================================================================
# Non-mutating host/config validation for init.sh and update.sh.
#
# Usage:
#   ./preflight.sh
#   ./preflight.sh --network
#   ./preflight.sh --json      # machine-readable output (see docs/cli-contract.md)
#
# Exits 1 if any check fails (both modes); warnings do not fail the run.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
PICSURE_ROOT="$SCRIPT_DIR"
export PICSURE_ROOT

LOG_PREFIX="preflight"
# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/scripts/lib/common.sh"
# shellcheck source=scripts/lib/config.sh
source "$SCRIPT_DIR/scripts/lib/config.sh"

# shellcheck source=scripts/picsure-compose.sh
source "$SCRIPT_DIR/scripts/picsure-compose.sh"

# shellcheck source=scripts/lib/json.sh
source "$SCRIPT_DIR/scripts/lib/json.sh"

NETWORK=false
FAILED=false
JSON=false
CHECKS=()
DAEMON_OK=false

# Detect --json first so result helpers know the mode even if an unknown
# option appears before it on the command line.
for arg in "$@"; do
  case "$arg" in
    --json) JSON=true ;;
  esac
done

# Each check has a stable name (documented in docs/cli-contract.md) plus a
# human message. Human mode prints exactly what it always did; JSON mode
# accumulates {name, status, message} objects instead.
add_check() {
  CHECKS+=("$(json_obj "$(json_str name "$1")" "$(json_str status "$2")" "$(json_str message "$3")")")
}

ok() {
  local name="$1"
  shift
  if [ "$JSON" = "true" ]; then
    add_check "$name" ok "$*"
  else
    echo -e "${PICSURE_GREEN}[ok]${PICSURE_NC} $*"
  fi
}

warn() {
  local name="$1"
  shift
  if [ "$JSON" = "true" ]; then
    add_check "$name" warn "$*"
  else
    echo -e "${PICSURE_YELLOW}[warn]${PICSURE_NC} $*"
  fi
}

fail() {
  local name="$1"
  shift
  FAILED=true
  if [ "$JSON" = "true" ]; then
    add_check "$name" fail "$*"
  else
    echo -e "${PICSURE_RED}[fail]${PICSURE_NC} $*" >&2
  fi
}

psection() {
  if [ "$JSON" != "true" ]; then
    echo "[preflight] $*"
  fi
}

for arg in "$@"; do
  case "$arg" in
    --network) NETWORK=true ;;
    --json) ;;
    -h|--help)
      sed -n '2,13p' "$0"
      exit 0
      ;;
    *)
      fail "args.unknown" "Unknown option: $arg"
      ;;
  esac
done

check_command() {
  local name="$1"
  local cmd="$2"
  local label="${3:-$2}"

  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$name" "$label found: $(command -v "$cmd")"
  else
    fail "$name" "$label not found."
  fi
}

check_required_env() {
  local key="$1"
  local value="${!key:-}"

  if [ -n "$value" ]; then
    ok "env.$key" "$key is set."
  else
    warn "env.$key" "$key is not set."
  fi
}

compose_config_ready() {
  local missing
  missing="$(picsure_compose_missing_generated_files "$SCRIPT_DIR" || true)"

  if [ -z "$missing" ]; then
    return 0
  fi

  while IFS= read -r path; do
    warn "compose.generated" "$path is generated by ./init.sh and is not present yet."
  done <<< "$missing"
  return 1
}

emit_json() {
  local top=()
  top+=("$(json_raw schema_version 1)")
  top+=("$(json_str command preflight)")
  top+=("$(json_bool network_checked "$NETWORK")")
  if [ "$FAILED" = "true" ]; then
    top+=("$(json_bool passed false)")
  else
    top+=("$(json_bool passed true)")
  fi
  top+=("$(json_raw checks "$(json_arr ${CHECKS[@]+"${CHECKS[@]}"})")")
  json_obj "${top[@]}"
  echo ""
}

cd "$SCRIPT_DIR"

psection "Host tools"
check_command host.git git Git
check_command host.docker docker Docker

if command -v uuidgen >/dev/null 2>&1; then
  ok host.uuid "UUID generation available through uuidgen."
elif [ -f /proc/sys/kernel/random/uuid ]; then
  ok host.uuid "UUID generation available through /proc/sys/kernel/random/uuid."
else
  fail host.uuid "UUID generation unavailable. Install uuidgen."
fi

if command -v jq >/dev/null 2>&1; then
  ok host.jq "jq found: $(command -v jq)"
else
  warn host.jq "jq not found; release-control.sh will use Docker image ${JQ_IMAGE:-ghcr.io/jqlang/jq:1.7.1}."
fi

if docker compose version >/dev/null 2>&1; then
  ok host.compose "Docker Compose available: $(docker compose version --short 2>/dev/null || docker compose version)"
else
  fail host.compose "Docker Compose V2 is not available through 'docker compose'."
fi

if docker info >/dev/null 2>&1; then
  DAEMON_OK=true
  ok host.daemon "Docker daemon is reachable."
else
  fail host.daemon "Docker daemon is not reachable."
fi

psection "Files"
for path in docker-compose.yml init.sh update.sh build-images.sh release-control.sh run-migrations.sh seed-db.sh config/scripts/generate-introspection-token.sh; do
  if [ -f "$path" ]; then
    ok "files.$path" "$path exists."
  else
    fail "files.$path" "$path is missing."
  fi
done

for path in init.sh update.sh build-images.sh release-control.sh run-migrations.sh seed-db.sh config/scripts/generate-introspection-token.sh; do
  if [ -x "$path" ]; then
    ok "exec.$path" "$path is executable."
  else
    fail "exec.$path" "$path is not executable."
  fi
done

psection "TLS"
# docker-compose.yml bind-mounts certs/server.key into httpd as an individual
# file, and Apache there runs as uid/gid 2 (daemon) — so the HOST mode decides
# whether SSL can start at all. A key uid 2 cannot read (0600 is openssl's
# default, and a reasonable mode for a production key an operator dropped in)
# aborts Apache's SSL init with "AH02574" before it binds: httpd goes unhealthy
# and 80/443 answer nothing, with nothing in the compose output naming the
# cause. init.sh generates its own key readable; this is here for the
# operator-supplied one it deliberately does not touch.
#
# Skipped on macOS: Docker Desktop's file sharing remaps ownership into the VM,
# so the host mode says nothing about what the container actually sees.
if [ ! -f certs/server.key ]; then
  warn tls.key.readable "certs/server.key is generated by ./init.sh and is not present yet."
elif [[ "$OSTYPE" =~ ^darwin ]]; then
  ok tls.key.readable "certs/server.key permissions not checked (Docker Desktop remaps ownership)."
else
  key_stat="$(stat -c '%a %u %g' certs/server.key 2>/dev/null || true)"
  read -r key_mode key_uid key_gid <<< "$key_stat"
  key_perm="$(( 8#${key_mode:-0} ))"
  if [ "$(( key_perm & 4 ))" -ne 0 ] ||
     { [ "${key_gid:-}" = "2" ] && [ "$(( key_perm & 32 ))" -ne 0 ]; } ||
     { [ "${key_uid:-}" = "2" ] && [ "$(( key_perm & 256 ))" -ne 0 ]; }; then
    ok tls.key.readable "certs/server.key is readable by httpd's uid 2 (mode ${key_mode:-unknown})."
  else
    fail tls.key.readable "certs/server.key (mode $key_mode, owner $key_uid:$key_gid) is unreadable by httpd's uid 2; Apache SSL init will fail. Fix: sudo chgrp 2 certs/server.key && sudo chmod 0640 certs/server.key"
  fi
fi

psection "Shell syntax"
for path in init.sh update.sh build-images.sh preflight.sh status.sh uninstall.sh release-control.sh bootstrap-remote-db.sh run-migrations.sh seed-db.sh load-demo-data.sh etl.sh scripts/lib/common.sh scripts/lib/json.sh scripts/picsure-compose.sh scripts/env-set.sh scripts/compose.sh scripts/db-wait.sh scripts/env-normalize.sh config/scripts/generate-introspection-token.sh; do
  if [ -f "$path" ]; then
    if bash -n "$path"; then
      ok "syntax.$path" "$path syntax is valid."
    else
      fail "syntax.$path" "$path has a shell syntax error."
    fi
  fi
done

psection "Environment"
if [ -f "$ENV_FILE" ]; then
  ok env.present ".env exists."
  if picsure_load_env "$ENV_FILE" 2>/dev/null; then
    check_required_env AUTH0_CLIENT_ID
    check_required_env AUTH0_CLIENT_SECRET
    check_required_env AUTH0_TENANT
    check_required_env ADMIN_EMAIL

    if picsure_theme_valid "${PICSURE_THEME:-picsure}"; then
      ok env.theme "PICSURE_THEME=${PICSURE_THEME:-picsure}"
    else
      fail env.theme "PICSURE_THEME must be picsure, bdc, aim-ahead, or local."
    fi

    if picsure_introspection_configured; then
      ok env.introspection_token "Introspection token is configured (signature and expiry not verified)."
    else
      warn env.introspection_token "Introspection token is missing, a placeholder, or contains whitespace; configure Auth0 and run init.sh before starting the gateway."
    fi

    case "${CONSENT_BASED_AUTHORIZATION_ENABLED:-false}" in
      false) ok env.consent_authorization "Consent authorization is disabled for AIO." ;;
      true) warn env.consent_authorization "Consent authorization requires populated user consents; query service PSAMA_URL=${PSAMA_URL:-http://psama:8090}." ;;
      *) fail env.consent_authorization "CONSENT_BASED_AUTHORIZATION_ENABLED must be true or false." ;;
    esac
    case "${GATEWAY_DOCS_ENABLED:-true}" in
      true|false) ok env.api_docs "GATEWAY_DOCS_ENABLED=${GATEWAY_DOCS_ENABLED:-true}" ;;
      *) fail env.api_docs "GATEWAY_DOCS_ENABLED must be true or false." ;;
    esac

    case "${DB_MODE:-local}" in
      local|remote) ok env.db_mode "DB_MODE=${DB_MODE:-local}" ;;
      *) fail env.db_mode "DB_MODE must be local or remote, got '${DB_MODE}'." ;;
    esac

    if [ "${DB_MODE:-local}" = "remote" ]; then
      check_required_env DB_HOST
      check_required_env DB_ROOT_USER
      check_required_env DB_ROOT_PASSWORD
    fi

    case "${HPDS_DATA_MODE:-local}" in
      local) ok env.hpds_data_mode "HPDS_DATA_MODE=local" ;;
      shared)
        if [ -z "${HPDS_SHARED_DATA:-}" ]; then
          fail env.hpds_data_mode "HPDS_DATA_MODE=shared requires HPDS_SHARED_DATA (a published data set name)."
        else
          ok env.hpds_data_mode "HPDS_DATA_MODE=shared, HPDS_SHARED_DATA=$HPDS_SHARED_DATA"
          # External volumes: Compose refuses to start HPDS when they are missing.
          if [ "$DAEMON_OK" != "true" ]; then
            warn hpds.shared_data "Skipping shared HPDS volume check; Docker daemon is not reachable."
          else
            missing_vols=()
            for kind in hpds-data hpds-genomic; do
              docker volume inspect "${HPDS_SHARED_DATA}_$kind" >/dev/null 2>&1 \
                || missing_vols+=("${HPDS_SHARED_DATA}_$kind")
            done
            if [ "${#missing_vols[@]}" -eq 0 ]; then
              ok hpds.shared_data "Shared HPDS volumes for '$HPDS_SHARED_DATA' exist."
            else
              fail hpds.shared_data "Missing shared HPDS volumes: ${missing_vols[*]}. Publish them with scripts/publish-shared-hpds-data.sh."
            fi
          fi
        fi
        ;;
      *) fail env.hpds_data_mode "HPDS_DATA_MODE must be local or shared, got '${HPDS_DATA_MODE}'." ;;
    esac

    case "${AUTH_MODE:-required}" in
      required|open|explore) ok env.auth_mode "AUTH_MODE=${AUTH_MODE:-required}" ;;
      *) fail env.auth_mode "AUTH_MODE must be required, open, or explore, got '${AUTH_MODE}'." ;;
    esac
  else
    fail env.parse ".env is not valid shell syntax; fix or regenerate it."
  fi
else
  warn env.present ".env is missing. Run: cp .env.example .env"
fi

psection "Compose"
if [ "$DAEMON_OK" != "true" ]; then
  warn compose.config "Skipping Compose config validation; Docker daemon is not reachable."
elif compose_config_ready; then
  if picsure_compose config --quiet; then
    ok compose.config "Compose config is valid."
  else
    fail compose.config "Compose config is invalid."
  fi
else
  warn compose.config "Skipping Compose config validation until generated init files exist."
fi

psection "Release control"
release_repo="${RELEASE_CONTROL_REPO:-https://github.com/hms-dbmi/baseline-pic-sure-release-control}"
release_branch="${RELEASE_CONTROL_BRANCH:-main}"
ok release.repo "RELEASE_CONTROL_REPO=$release_repo"
ok release.branch "RELEASE_CONTROL_BRANCH=$release_branch"

if [ -d "$SCRIPT_DIR/.data/release-control/.git" ]; then
  ok release.cache "Release-control cache exists at .data/release-control."
else
  warn release.cache "Release-control cache is missing; init/update will clone it."
fi

psection "JWT creator"
jwt_repo="${JWT_CREATOR_REPO:-https://github.com/hms-dbmi/jwt-creator.git}"
jwt_ref="${JWT_CREATOR_REF:-v1.0.0}"
jwt_dir="${JWT_CREATOR_DIR:-$SCRIPT_DIR/.data/jwt-creator}"
ok jwt.repo "JWT_CREATOR_REPO=$jwt_repo"
if [ "$jwt_ref" = "v1.0.0" ]; then
  ok jwt.ref "JWT_CREATOR_REF=$jwt_ref"
else
  warn jwt.ref "JWT_CREATOR_REF=$jwt_ref (default is v1.0.0)."
fi

if [ -f "$jwt_dir/target/generateJwt.jar" ]; then
  ok jwt.jar "jwt-creator jar is cached."
else
  warn jwt.jar "jwt-creator jar is not cached; first token generation will clone/build it with Docker."
fi

if [ "$NETWORK" = "true" ]; then
  psection "Network"
  if git ls-remote --heads "$release_repo" "$release_branch" >/dev/null 2>&1 || git ls-remote --tags "$release_repo" "$release_branch" >/dev/null 2>&1; then
    ok network.release-control "Release-control ref is reachable."
  else
    fail network.release-control "Release-control branch/tag '$release_branch' is not reachable at $release_repo."
  fi

  if git ls-remote --tags "$jwt_repo" "$jwt_ref" >/dev/null 2>&1 || git ls-remote --heads "$jwt_repo" "$jwt_ref" >/dev/null 2>&1; then
    ok network.jwt-creator "jwt-creator ref is reachable."
  else
    fail network.jwt-creator "jwt-creator ref '$jwt_ref' is not reachable at $jwt_repo."
  fi
else
  warn network.skipped "Skipping network checks. Use --network to verify remote release-control and jwt-creator refs."
fi

if [ "$JSON" = "true" ]; then
  emit_json
  if [ "$FAILED" = "true" ]; then
    exit 1
  fi
  exit 0
fi

if [ "$FAILED" = "true" ]; then
  echo "[preflight] Failed." >&2
  exit 1
fi

echo "[preflight] Passed."
