#!/usr/bin/env bash
# =============================================================================
# PIC-SURE — Reset Environment
# =============================================================================
# Tears down containers and generated config so you can re-run init.sh cleanly.
# Backs up .env before removing anything. Does NOT touch:
#   - The database volume (picsure-db data persists)
#   - Sibling repos
#   - .env.example
#
# Usage:
#   ./reset.sh              # Reset config + containers (keep DB)
#   ./reset.sh --all        # Also remove database volume (full wipe)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
PROJECT_NAME="${COMPOSE_PROJECT_NAME:-picsure}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[reset]${NC} $*"; }
warn()  { echo -e "${YELLOW}[reset]${NC} $*"; }
error() { echo -e "${RED}[reset]${NC} $*" >&2; }

WIPE_DB=false
[[ "${1:-}" == "--all" ]] && WIPE_DB=true

echo ""
if [ "$WIPE_DB" = "true" ]; then
  warn "⚠  FULL RESET — this will delete everything including the database."
else
  info "Resetting environment (database volume will be preserved)."
fi
echo ""

# -------------------------------------------------------------------------
# Step 1: Back up .env
# -------------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  BACKUP="$ENV_FILE.backup.$(date +%Y%m%d-%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  info "Backed up .env → $(basename "$BACKUP")"
fi

# -------------------------------------------------------------------------
# Step 2: Stop and remove containers
# -------------------------------------------------------------------------
info "Stopping containers..."
docker compose -f "$SCRIPT_DIR/docker-compose.yml" down 2>/dev/null || true

# -------------------------------------------------------------------------
# Step 3: Remove volumes (except DB unless --all)
# -------------------------------------------------------------------------
DB_VOLUME="${PROJECT_NAME}_picsure-db-data"

# Get all project volumes
VOLUMES=$(docker volume ls --filter "name=${PROJECT_NAME}_" --format '{{.Name}}' 2>/dev/null || true)

for vol in $VOLUMES; do
  if [ "$vol" = "$DB_VOLUME" ] && [ "$WIPE_DB" != "true" ]; then
    warn "Keeping database volume: $vol"
    continue
  fi
  docker volume rm "$vol" 2>/dev/null && info "Removed volume: $vol" || true
done

# -------------------------------------------------------------------------
# Step 4: Remove generated config files
# -------------------------------------------------------------------------
info "Removing generated config..."

# Generated by init.sh
rm -f "$ENV_FILE"
rm -rf "$SCRIPT_DIR/certs"
rm -f "$SCRIPT_DIR/config/dictionary/dictionary.env"
rm -f "$SCRIPT_DIR/config/hpds/encryption_key"
rm -f "$SCRIPT_DIR/config/wildfly/application.truststore"
rm -f "$SCRIPT_DIR/config/psama/application.truststore"
rm -f "$SCRIPT_DIR/config/wildfly/visualization/pic-sure-visualization-resource/resource.properties"
rm -rf "$SCRIPT_DIR/.data"

# WAR files (copied/built)
rm -f "$SCRIPT_DIR/config/wildfly/deployments/"*.war

info "Generated config removed."

# -------------------------------------------------------------------------
# Step 5: Remove images (--all only)
# -------------------------------------------------------------------------
if [ "$WIPE_DB" = "true" ]; then
  info "Removing PIC-SURE images..."
  for img in pic-sure-hpds pic-sure-psama pic-sure-wildfly pic-sure-httpd \
             pic-sure-dictionary-api pic-sure-dictionary-dump pic-sure-hpds-etl; do
    docker rmi "hms-dbmi/$img:${PICSURE_IMAGE_TAG:-LATEST}" 2>/dev/null && \
      info "Removed image: hms-dbmi/$img" || true
  done
  # Remove Maven cache volume (forces full rebuild)
  docker volume rm maven_m2_cache 2>/dev/null && \
    info "Removed Maven cache volume." || true
fi

# -------------------------------------------------------------------------
# Done
# -------------------------------------------------------------------------
echo ""
info "======================================"
info "  Reset complete!"
info "======================================"
echo ""
if [ -f "$BACKUP" ]; then
  info "Your .env was backed up to: $(basename "$BACKUP")"
  info "To restore: cp $(basename "$BACKUP") .env"
fi
echo ""
info "To start fresh:"
info "  1. cp .env.example .env    # or restore your backup"
info "  2. Edit .env with your Auth0 credentials"
info "  3. ./init.sh"
info "  4. docker compose up -d"
if [ "$WIPE_DB" = "true" ]; then
  info "  5. ./seed-db.sh"
  info "  6. docker compose restart wildfly psama"
  info "  7. ./load-demo-data.sh"
fi
echo ""
