---
version: '3'
services:
  picsure-db:
    image: mysql:8.0
    container_name: picsure-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $PICSURE_DB_ROOT_PASS
      MYSQL_PASSWORD: $PICSURE_DB_PASS
      MYSQL_DATABASE: $PICSURE_DB_DATABASE
      MYSQL_USER: $PICSURE_DB_USER
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-p$PICSURE_DB_ROOT_PASS" ]
      timeout: 20s
      retries: 10
    volumes:
      - $DOCKER_CONFIG_DIR/picsure-db:/var/lib/mysql
    networks:
      - picsure
networks:
  picsure:
    external: true
